language: "en-US"

reviews:
  profile: "assertive"
  high_level_summary: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  path_filters:
    - "src/**"
    - "!src/drizzle/*"
  auto_review:
    enabled: true
    auto_incremental_review: true # Set false if don't want auto review when push any commit
    labels:
      - ai-review
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: "off"
      threshold: 80
    title:
      mode: "warning"
      requirements: "Title should start with a verb, be syntactically correct, and ideally be under 50 characters"
    description:
      mode: "off"
    issue_assessment:
      mode: "warning"
    custom_checks: []
  tools:
    ast-grep:
      rule_dirs:
        - rules
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: "default"
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: false
    eslint:
      enabled: true
    flake8:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: false
    sqlfluff: 
      enabled: false
    prismaLint:
      enabled: true
    pylint:
      enabled: false
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: true
    brakeman:
      enabled: false
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true

chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: "auto"
    linear:
      usage: "auto"

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "coding-rules.md"
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    usage: "auto"
    project_keys: []
  linear:
    usage: "auto"
    team_keys: []
  pull_requests:
    scope: "auto"
  mcp:
    usage: "disabled"

code_generation:
  docstrings:
    language: "en-US"
    path_instructions: []

  unit_tests:
    path_instructions: []